# Generated by Django 5.1.2 on 2024-10-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("riot_ID", models.CharField(max_length=30)),
                ("experience", models.PositiveIntegerField(default=0)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("duelist", "Duelist"),
                            ("controller", "Controller"),
                            ("sentinel", "Sentinel"),
                            ("initiator", "Initiator"),
                        ],
                        max_length=30,
                    ),
                ),
                ("statistics", models.URLField()),
                ("discord", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
